/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElTree: typeof import('element-plus/es')['ElTree']
  const ElTreeInstance: typeof import('element-plus/es')['ElTreeInstance']
  const ElTreeRef: typeof import('element-plus/es')['ElTreeRef']
  const ElTreeRef2: typeof import('element-plus/es')['ElTreeRef2']
}
